### PR TITLE
Add trial and map functionality to the AlfamaVR project

### PR DESCRIPTION
**Pull request by RoboDoig**
This PR adds the trial structure and map functionality required for EC experiments in AlfamaVR.

The TrialManager component allows users to define the trial sequence according to scenario, inter-trial times etc.

Also adds an automatic map generator for the environment via a second orthogonal camera that renders to a RenderTexture and then to the UI.

### CODE REVIEW

**Review by glopesdev — COMMENTED** [review]
Why not move TextMesh Pro to the `Objects` folder? Seems like we are making a local copy of this asset package and perhaps we could save some space on the repo and reduce the complexity of this PR.

Might require force pushing or git-filter-repo to remove the versioned files.

**Comment by RoboDoig** [comment]
> Why not move TextMesh Pro to the `Objects` folder? Seems like we are making a local copy of this asset package and perhaps we could save some space on the repo and reduce the complexity of this PR.
> 
> Might require force pushing or git-filter-repo to remove the versioned files.

If anyone has time to open the project can they check something for me (so I know I'm not going nuts). Is the TextMesh Pro folder hidden in the Unity editor but not in file explorer for anyone else?

**Comment by RoboDoig** [comment]
Looked into it this morning, TMP does not need to be tracked in the repo as long as the top level .meta file for TMP usage is preserved. When building the project from scratch, Unity will give a popup that asks the user if they want to import the TMP resources. Since this popup only appears if you click something with a TMP component in the scene view I've updated the readme with instructions for explicitly importing the TMP resources.

I've also updated the readme with instructions for the windows mixed reality import tool. The previous instructions directed the user to do a restore on the packages which I've found to be unreliable, seems to work better if you use discover features and explicitly import the required packages.

Will wait for feeback on this before using `filter-repo` to remove the TMP asset references from the branch.

**Review by glopesdev — APPROVED** [review]
LGTM feel free to try out the `filter-repo`

**Comment by RoboDoig** [comment]
filter-repo done

**Pull request merged**
